name: radio_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  record_platform_interface: ^1.2.0
  record_linux: ^1.2.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & animations
  marquee: ^2.2.3

  # AUDIO
  just_audio: ^0.9.46
  just_audio_media_kit: ^1.0.0          # Windows & Linux
  just_audio_background: ^0.0.1-beta.7  # background + notification
  media_kit: ^1.1.10
  media_kit_libs_audio: ^1.0.2
  media_kit_libs_windows_audio: ^1.0.2  # Windows
  media_kit_libs_linux: ^1.0.0          # Linux
  media_kit_libs_macos_audio: ^1.0.2    # macOS
  record: ^5.0.4                        # enregistrement + permissions

  # UTILITAIRES
  http: ^1.5.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  html: ^0.15.6
  path_provider: ^2.1.0
  permission_handler: ^11.3.1           # permissions (doublon supprimé)
  encrypt: ^5.0.3
  workmanager: ^0.5.2                   # à côté de shared_preferences, etc.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/localization/en.json
    - lib/localization/fr.json
    - lib/localization/es.json
    - lib/localization/ar.json
    - assets/countries.json
    - assets/default_logo.png
    - assets/lst_rdo.aes

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/custom-regular.ttf
          weight: 700