name: Update encrypted asset

on:
  push:
    paths:
      - '.github/workflows/lst_rdo.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate encrypted asset
        run: flutter run tool/encrypt_json.dart

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/lst_rdo.aes
          git diff --cached --quiet || (git commit -m "chore: auto-update encrypted asset" && git push)
